---
title: "AAVSO-Zapper.Rmd"
author: "David J Jackson"
date: "2/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(plotly)

```

## R Markdown
```{r}
rm(list=ls())
AOri <-fread("../db/Alf_Ori-corrected.csv")
AOri$Ymd <- as.Date(paste(AOri$year, AOri$month, AOri$day, sep = "-"))
AOri <- AOri %>% select(Ymd,year,month,day,Vis) 
AOri$Cts <- ifelse(AOri$Vis==0.00,0,1)
# Ori$Loess <-lowess(AOri$Vis,f=0.1)
summary(AOri)
```
```{r CAlculate Daily Stats}
 AOri1 <- AOri %>% select(Ymd,year,Vis) %>%
   group_by(Ymd) %>% summarise(Mean = mean(Vis),
                               Sum = sum(Vis),
                               Obs = n())
head(AOri1)
         
```
```{r}
AOri1$Dim <- AOri1$Mean + 1
AOri1$Bright <- AOri1$Mean - 1
head(AOri1)
```
```{r}
AOri1_merg <- merge(AOri,AOri1,by="Ymd")
AOri1_merged <- AOri1_merg %>% select(Ymd,Vis,Mean,Dim,Bright) %>%
  filter(Ymd >="1964-01-01") 
```
```{r}
AOri1_merged %>% select(Ymd) %>% group_by(Ymd) %>% summarise(count = n())
```
```{r}
 AOri1_merged$Zap <- AOri1_merged$Dim - AOri1_merged$Dim
```
```{r}
AOri$MA <- forecast::ma(AOri$Vis,order=30)
plot_ly(AOri) %>% add_lines(x=~Ymd,y=~MA)
```

