---
title: "Alf_Ori(Betelgeuse) Predictions-v1.0"
author: "David J Jackson & Rodney Howe"
date: "2/8/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#remotes::install_github("RamiKrispin/forecastLM")
library(tidyverse)
library(forecastLM)
library(data.table)
library(lubridate)
library(forecast)
library(tsibble)
library(epitools)
library(plotly)
```

```{r Import Alf Ori Date, echo=FALSE}
rm(list=ls())
AOri <-fread("../db/Alf_Ori-corrected.csv")
AOri <- AOri %>% select(year,month,day,Vis)
AOri$Cts <- ifelse(AOri$Vis==0.00,0,1)
# Ori$Loess <-lowess(AOri$Vis,f=0.1)
AOri$Ymd <- as.Date(paste(AOri$year, AOri$month, AOri$day, sep = "-")) 
summary(AOri)
```
```{r Calculate Daily Means, echo=FALSE}
 AOri1 <- AOri %>% select(Ymd,Vis) %>%
   group_by(Ymd) %>% summarise(Mean = mean(Vis),
                               Sum = sum(Vis),
                             Obs = n())
                                        
```


```{r, echo=FALSE, echo=FALSE}
colnames(AOri1) <- c("Ymd","Mean","Sum","Obs")
Mag <- tsibble::as_tsibble(AOri1,index="Ymd")
md <- trainLM(input = Mag,
              y = "Mean",
              trend = list(linear = TRUE),
              seasonal = "week",
              lags = c(1, 12))
```

#  Forecasting the future observations
```{r, echo=FALSE}
fc <- forecastLM(model = md,
                 h = 1000)
```

# Plotting the forecast output
```{r}
plot_fc(fc)
```


# Plotting the Fitted Values vs. Actuals
```{r,echo=FALSE}
plot_fit(md)
```

# Plotting the residuals
```{r,echo=FALSE}
plot_res(md)
```
```{r, echo=FALSE}

AOri$MA <- ma(AOri$Vis,order=60)
A <- AOri %>% filter(Ymd >="2014-01-01")
#fcc <- fc$forecast$date
fcc <- fc$forecast$Ymd
fcc <- data.table::as.data.table(fcc)
fcc$yhat <- fc$forecast$yhat
colnames(fcc) <- c("Ymd","Yhat")
fcc %>%filter(Ymd>="2020-02-01") 
head(fcc)
```
```{r}
plot_ly(fcc) %>% add_lines(x=~Ymd,y=~Yhat) %>%
  add_lines(data=A,x=~Ymd,y=~MA) %>%
  layout(yaxis=list(autorange="reversed"))

```
# Betelgeuse Complete set from AAVSO

```{r Betelgeuse Betelgeuse Betelgeuse,ech=FALSE}
betel <- fread("../db/Betelgeuse.txt")
betel <- janitor::clean_names(betel)
betel$magnitude <- as.numeric(betel$magnitude)
# betel$Ymd <- julian2date(betel$jd)


```
```{r,echo=FALSE}

betel_sum  <- betel %>% select(jd,star_name,magnitude,band) %>%
      group_by(band) %>% summarise( Count = n()) 
# betel_sum$band <- as.factor(betel_sum$band)
summary(betel_sum)

```
```{r, echo=FALSE}
betel_clean <- tsclean(betel$magnitude)
summary(betel$magnitude)
```